### PR TITLE
ADAP-973: Fix issue where materialized views were being mapped as views in catalog queries

### LINKED ISSUE #652: [ADAP-973] [Bug] Materialized views show up as regular views in catalog queries
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Materialized views show up as regular views in catalog queries.

### Expected Behavior

Materialized views should show up as materialized views in catalog queries.

### Steps To Reproduce

1. Create a materialized view
2. Run `docs generate`
3. Notice the type for the materialized view is "VIEW"

See https://github.com/dbt-labs/dbt-core/issues/8864 for more details.

### Relevant log output

_No response_

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mikealfare**
resolves #652, dbt-labs/dbt-core#8864

### Problem

Materialized views show up as views in catalog queries.

### Solution

- write a test demonstrating the issue
- update the catalog query to correctly assign type for materialized views

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt/include/redshift/macros/catalog.sql [hunk 1]
```diff
@@ -23,13 +23,28 @@
...
+            table_schema  as nspname,
+            table_name    as relname
+        from information_schema.views
+        where (
+            {%- for schema in schemas -%}
+                upper(table_schema) = upper('{{ schema }}'){%- if not loop.last %} or {% endif -%}
+            {%- endfor -%}
+        )
+        and table_catalog = '{{ database }}'
+        and view_definition ilike '%create materialized view%'
```
Comment (VersusFacit) [inline dbt/include/redshift/macros/catalog.sql:37]: This will be performance intensive. Is there a faster (regex?) alternative?

**Review by VersusFacit — COMMENTED** [review]
One nit. Otherwise, straightforward. May want to leave a comment about the `case`-`when` being a short circuit operation though. The important of that precedence of checking the view is materialized first could be lost without that context somewhere.

File: dbt/include/redshift/macros/catalog.sql (hunk 1 above)
Comment (mikealfare) [reply dbt/include/redshift/macros/catalog.sql:37]: Oh, perhaps. But we're already doing this in `list_relations_without_caching`. To my knowledge, there's no good way to do this check.

**Comment by mikealfare** [comment]
> One nit. Otherwise, straightforward. May want to live a comment about the `case`-`when` being a short circuit operation though. The important of that precedence of checking the view is materialized first could be lost without that context somewhere.

That's a good point. I chose instead to add the condition in the case statement. Let me know what you think.

**Review by colin-rogers-dbt — APPROVED** [review]

File: dbt/include/redshift/macros/catalog.sql (hunk 1 above)
Comment (VersusFacit) [reply dbt/include/redshift/macros/catalog.sql:37]: Hmmm, fair enough. I appreciate the point about maintaining state of the art for now.

**Review by VersusFacit — APPROVED** [review]
